version: '3.1'

# secrets:

#   nginx_ssl_bundle:
#     file: ./certs/ssl-bundle.crt

#   nginx_ssl_private_key:
#     file: ./certs/carlosduclos.dev.key

services:

  mongodb:
    container_name: mongodb
    image: darkzeratul64/webrtc-mongodb:latest
    restart: always
    command: ["--bind_ip_all"]
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

  redis:
    container_name: redis
    image: darkzeratul64/webrtc-redis:latest
    ports:
      - 6379:6379
    networks:
      - backend

  signaling_server_prod:
    container_name: signaling_server_prod
    image: darkzeratul64/webrtc-signalingserver:latest
    ports:
      - 9000:9000
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis
    networks:
      - backend

  videoconference_app_prod:
    container_name: videoconference_app_prod
    build:
      context: .
      dockerfile: ./Dockerfile-videoconference-with-certs.prod
    # image: darkzeratul64/webrtc-videoconference:latest
    stdin_open: true
    links:
      - signaling_server_prod
    # secrets:
    #   - nginx_ssl_bundle
    #   - nginx_ssl_private_key

    # tty: true
    # volumes:
    #   - ./certs:/etc/ssl/app
    ports:
      - 80:80
      - 443:443
    networks:
      - backend

  coturn: 
    container_name: coturn
    image: darkzeratul64/webrtc-coturn:latest
    restart: unless-stopped
    # network_mode: host
    ports:
      - 5349:5349
      - 3478:3478
      # - "1-65535:1-65535"
    command:
      - -c /etc/coturn/turnserver.conf
      - --log-file=stdout
      - --external-ip=$$(detect-external-ip)
      - --no-cli
    networks:
      - backend

networks:
    backend: